# Generated by Django 5.0 on 2024-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
